const categorias = {
  Cozinha: [
    "Frango",
    "Carne",
    "Filé",
    "Camarão",
    "Coracao de Frango",
    "Piracuí",
    "Pirarucu",
    "Jambú",
    "Tucupi",
    "Manjericão",
    "Cheiro Verde",
    "Óleo",
    "Leite Caixa",
    "Batata Palha",
    "Macaxeira Chips",
    "Orégano",
    "Gás",
    "Alho",
    "Tempero Arisco",
    "Vinagre",
    "Sal",
    "Café",
    "Açúcar",
    "Sazón",
    "Saco Molho Verde",
    "Caldo Carne",
    "Caldo Frango",
    "Coloral",
    "Pimenta Reino",
    "Pimenta Cheiro",
    "Isqueiro",
  ],
  Limpeza: [
    "Detergente",
    "Desinfetante",
    "Sabão Pó",
    "Sabão Barra",
    "Veja",
    "Esponja",
    "Bombril",
    "Palha de Aço",
    "Água Sanitária",
    "Limpa Alumínio",
  ],
  Mesa: [
    "Cebola",
    "Tomate",
    "Pimentão",
    "Calabresa",
    "Presunto",
    "Bacon",
    "Milho",
    "Ervilha",
    "Azeitona",
    "Molho Vermelho",
    "Ovos",
    "Catupiry",
    "Cheddar",
    "Queijo Parmesão",
    "Queijo Qualho",
    "Queijo Provolone",
    "Queijo Prato",
    "Maionese Grande",
    "Salame",
    "Lombo Canadense",
    "Palmito",
    "Creme de Leite",
    "Leite Condensado",
    "Goiabada",
    "Chocolate",
    "Chocolate Granulado",
    "MMs",
    "Cupuaçu",
    "Banana",
    "Abacaxi",
    "Pessego",
    "Cereja",
    "Ameixa Seca",
    "Barbecue",
    "Azeite Camarão",
    "Pimenta Gota",
  ],
  "Massas e Caixas": [
    "Massa Media",
    "Massa Grande",
    "Massa Familia",
    "Massa Gigante",
    "Caixa Media",
    "Caixa Grande",
    "Caixa Familia",
    "Caixa Gigante",
  ],
  Balcão: [
    "Ketchup Sachê",
    "Maionese Sachê",
    "Saco Sache",
    "Saco Plastico",
    "Copo Descartável",
    "Prato Descartável",
    "Guardanapos",
    "Talher Descartável",
    "Fita Adesiva",
    "Bobinha Comanda",
    "Coca 1L",
    "Coca 1.5L",
    "Coca 2L",
    "Coca 2.5L",
    "Fanta 1L",
    "Fanta 1.5L",
    "Fanta 2L",
    "Baré 1L",
    "Baré 1.5L",
    "Baré 2L",
    "Guaraná 1L",
    "Guaraná 1.5L",
    "Guaraná 2L",
  ],
};
